# Generated by Django 4.1.1 on 2022-11-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baumkataster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='user_list',
            field=models.ManyToManyField(to='baumkataster.user'),
        ),
    ]
