# Generated by Django 4.1.1 on 2022-11-30 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baumkataster', '0002_tree_user_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
