# Generated by Django 4.1.1 on 2022-12-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baumkataster', '0003_remove_user_email_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='oid',
            field=models.IntegerField(default=0),
        ),
    ]
