# Generated by Django 4.1.1 on 2022-12-14 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baumkataster', '0004_rename_kind_tree_care_kind_tree_oid'),
        ('baumkataster', '0004_tree_oid'),
    ]

    operations = [
    ]
